// example/lib/screens/export_screen.dart
//
// Export screen – generate license reports and activity logs in
// multiple formats (plain text, JSON, Markdown, CSV).
// Uses LicenseExportService from the app_shield package.

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:provider/provider.dart';
import 'package:app_shield/app_shield.dart';

import '../widgets/info_card.dart';

class ExportScreen extends StatefulWidget {
  const ExportScreen({super.key});

  @override
  State<ExportScreen> createState() => _ExportScreenState();
}

class _ExportScreenState extends State<ExportScreen> {
  LicenseExportFormat _selectedFormat = LicenseExportFormat.markdown;
  LicenseExportResult? _lastResult;
  bool _isExporting = false;

  static const _formats = [
    (LicenseExportFormat.markdown,  'Markdown',   Icons.description_outlined),
    (LicenseExportFormat.plainText, 'Plain Text', Icons.text_snippet_outlined),
    (LicenseExportFormat.json,      'JSON',       Icons.data_object_outlined),
    (LicenseExportFormat.csv,       'CSV',        Icons.table_chart_outlined),
  ];

  Future<void> _exportLicense(License license) async {
    setState(() => _isExporting = true);
    await Future.delayed(const Duration(milliseconds: 120)); // let UI breathe

    final result = LicenseExportService.instance.exportLicense(
      license: license,
      format:  _selectedFormat,
      extra:   {
        'Generated By': 'AppShield Demo App',
        'App Version':  '1.0.0',
        'Platform':     'Windows',
      },
    );

    setState(() {
      _lastResult   = result;
      _isExporting  = false;
    });
  }

  Future<void> _exportLog(List<ActivityLogEntry> entries) async {
    setState(() => _isExporting = true);
    await Future.delayed(const Duration(milliseconds: 120));

    final result = LicenseExportService.instance.exportActivityLog(
      entries: entries,
      format:  _selectedFormat,
    );

    setState(() {
      _lastResult  = result;
      _isExporting = false;
    });
  }

  Future<void> _copyToClipboard() async {
    if (_lastResult == null) return;
    await Clipboard.setData(ClipboardData(text: _lastResult!.content));
    if (mounted) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text('Copied ${_lastResult!.filename} to clipboard!'),
          duration: const Duration(seconds: 2),
        ),
      );
    }
  }

  @override
  Widget build(BuildContext context) {
    return Consumer<AppShieldProvider>(
      builder: (context, shield, _) {
        final license = shield.license;

        return ListView(
          padding: const EdgeInsets.all(20),
          children: [
            // ── Format selector ──────────────────────────────────────────
            SectionTitle('Export Format', icon: Icons.tune_outlined),
            _FormatSelector(
              formats:        _formats,
              selected:       _selectedFormat,
              onSelect:       (f) => setState(() => _selectedFormat = f),
            ),
            const SizedBox(height: 20),

            // ── Export buttons ───────────────────────────────────────────
            SectionTitle('Export Actions', icon: Icons.file_download_outlined),
            InfoCard(
              child: Column(
                children: [
                  // License report
                  ListTile(
                    leading: Container(
                      padding: const EdgeInsets.all(8),
                      decoration: BoxDecoration(
                        color:        AppShieldColors.primary.withAlpha(25),
                        borderRadius: BorderRadius.circular(8),
                      ),
                      child: const Icon(Icons.badge_outlined,
                          color: AppShieldColors.primary),
                    ),
                    title:    const Text('License Report'),
                    subtitle: const Text(
                        'Export full license details including features and limits'),
                    trailing: _isExporting
                        ? const SizedBox(
                            width:  20,
                            height: 20,
                            child:  CircularProgressIndicator(strokeWidth: 2))
                        : FilledButton(
                            onPressed: license != null
                                ? () => _exportLicense(license)
                                : null,
                            child: const Text('Export'),
                          ),
                  ),
                  const Divider(height: 1),

                  // Activity log
                  ListTile(
                    leading: Container(
                      padding: const EdgeInsets.all(8),
                      decoration: BoxDecoration(
                        color:        AppShieldColors.info.withAlpha(25),
                        borderRadius: BorderRadius.circular(8),
                      ),
                      child: const Icon(Icons.history_outlined,
                          color: AppShieldColors.info),
                    ),
                    title:    const Text('Activity Log'),
                    subtitle: const Text(
                        'Export all license events and activity entries'),
                    trailing: _isExporting
                        ? const SizedBox(
                            width:  20,
                            height: 20,
                            child:  CircularProgressIndicator(strokeWidth: 2))
                        : FilledButton(
                            onPressed: () async {
                              if (!AppShield.isInitialized) return;
                              final entries =
                                  await AppShield.instance.getActivityLog();
                              if (mounted) _exportLog(entries);
                            },
                            child: const Text('Export'),
                          ),
                  ),
                ],
              ),
            ),
            const SizedBox(height: 20),

            // ── Result preview ────────────────────────────────────────────
            if (_lastResult != null) ...[
              Row(
                children: [
                  Expanded(
                    child: SectionTitle(
                      'Preview: ${_lastResult!.filename}',
                      icon: Icons.preview_outlined,
                    ),
                  ),
                  IconButton(
                    icon:    const Icon(Icons.copy, size: 18),
                    tooltip: 'Copy to clipboard',
                    onPressed: _copyToClipboard,
                  ),
                  IconButton(
                    icon:    const Icon(Icons.close, size: 18),
                    tooltip: 'Clear preview',
                    onPressed: () => setState(() => _lastResult = null),
                  ),
                ],
              ),
              _ExportPreviewCard(result: _lastResult!),
            ],

            // ── Format descriptions ───────────────────────────────────────
            const SizedBox(height: 20),
            SectionTitle('Format Guide', icon: Icons.help_outline),
            _FormatGuide(),
          ],
        );
      },
    );
  }
}

// ── Format selector ───────────────────────────────────────────────────────

class _FormatSelector extends StatelessWidget {
  const _FormatSelector({
    required this.formats,
    required this.selected,
    required this.onSelect,
  });

  final List<(LicenseExportFormat, String, IconData)> formats;
  final LicenseExportFormat                           selected;
  final ValueChanged<LicenseExportFormat>             onSelect;

  @override
  Widget build(BuildContext context) {
    return Wrap(
      spacing:    10,
      runSpacing: 10,
      children: formats.map((f) {
        final (fmt, label, icon) = f;
        final isSelected = fmt == selected;
        final color = isSelected
            ? AppShieldColors.primary
            : Theme.of(context).colorScheme.outline;

        return InkWell(
          borderRadius: BorderRadius.circular(10),
          onTap: () => onSelect(fmt),
          child: Container(
            padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 10),
            decoration: BoxDecoration(
              color:        isSelected
                  ? AppShieldColors.primary.withAlpha(20)
                  : Colors.transparent,
              borderRadius: BorderRadius.circular(10),
              border:       Border.all(
                color:     color,
                width:     isSelected ? 2 : 1,
              ),
            ),
            child: Row(
              mainAxisSize: MainAxisSize.min,
              children: [
                Icon(icon, size: 16, color: color),
                const SizedBox(width: 6),
                Text(label,
                    style: TextStyle(
                      color:      color,
                      fontWeight: isSelected
                          ? FontWeight.bold
                          : FontWeight.normal,
                    )),
              ],
            ),
          ),
        );
      }).toList(),
    );
  }
}

// ── Export preview card ───────────────────────────────────────────────────

class _ExportPreviewCard extends StatelessWidget {
  const _ExportPreviewCard({required this.result});
  final LicenseExportResult result;

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    return InfoCard(
      padding: EdgeInsets.zero,
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: [
          // Header bar
          Container(
            padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 10),
            decoration: BoxDecoration(
              color:        theme.colorScheme.surfaceContainerHighest
                  .withAlpha(120),
              borderRadius: const BorderRadius.vertical(
                  top: Radius.circular(12)),
            ),
            child: Row(
              children: [
                Icon(Icons.article_outlined, size: 14,
                    color: theme.colorScheme.primary),
                const SizedBox(width: 6),
                Text(
                  result.filename,
                  style: theme.textTheme.labelSmall?.copyWith(
                    fontFamily: 'Courier New',
                    fontWeight: FontWeight.bold,
                  ),
                ),
                const Spacer(),
                Text(
                  '${result.content.length} chars',
                  style: theme.textTheme.labelSmall?.copyWith(
                    color: theme.colorScheme.onSurfaceVariant,
                  ),
                ),
              ],
            ),
          ),
          // Content
          SizedBox(
            height: 320,
            child: SingleChildScrollView(
              padding: const EdgeInsets.all(16),
              child: SelectableText(
                result.content,
                style: const TextStyle(
                  fontFamily: 'Courier New',
                  fontSize:   12,
                  height:     1.5,
                ),
              ),
            ),
          ),
        ],
      ),
    );
  }
}

// ── Format guide ──────────────────────────────────────────────────────────

class _FormatGuide extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    const entries = [
      (Icons.description_outlined, 'Markdown (.md)',
          'Human-readable with headers, tables, and checkboxes. '
          'Best for documentation and README files.'),
      (Icons.text_snippet_outlined, 'Plain Text (.txt)',
          'Simple text format with ASCII art. '
          'Universal — can be opened in any text editor.'),
      (Icons.data_object_outlined, 'JSON (.json)',
          'Machine-readable structured data. '
          'Best for APIs, integrations, and developers.'),
      (Icons.table_chart_outlined, 'CSV (.csv)',
          'Spreadsheet-compatible format. '
          'Best for activity logs and bulk data analysis.'),
    ];

    return InfoCard(
      child: Column(
        children: entries.map((e) {
          final (icon, title, desc) = e;
          return Padding(
            padding: const EdgeInsets.symmetric(vertical: 8),
            child: Row(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Icon(icon, size: 18,
                    color: Theme.of(context).colorScheme.primary),
                const SizedBox(width: 12),
                Expanded(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text(title,
                          style: const TextStyle(
                              fontWeight: FontWeight.w600, fontSize: 13)),
                      const SizedBox(height: 2),
                      Text(desc,
                          style: TextStyle(
                            fontSize: 12,
                            color: Theme.of(context)
                                .colorScheme
                                .onSurfaceVariant,
                          )),
                    ],
                  ),
                ),
              ],
            ),
          );
        }).toList(),
      ),
    );
  }
}
